config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'
  
  get 'students/new'
  
  get 'letters/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  get 'new_student'   => 'students#new'
  get 'new_letter'   => 'letters#new'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,  only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :students do 
    resources :letters
  end

end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
  has_many :letters, dependent: :destroy
  default_scope -> { order(:name) }
  validates :user_id, presence: true
  validates :name, presence: true
  validates :gender, presence: true
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update, :destroy]
  
  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = current_user.students.build(student_params)
    if @student.save
      flash[:success] = "Student created!"
      redirect_to @student
    else
      render 'new'
    end
  end
  
  def edit
    @student = Student.find(params[:id])
  end
  
  def update
    @student = Student.find(params[:id])
    if @student.update_attributes(student_params)
      flash[:success] = "Student updated"
      redirect_to @student
    else
      render 'edit'
    end
  end
  
  def destroy
    @student = Student.find(params[:id])
    @user = @student.user
    @student.destroy
    flash[:success] = "Student deleted"
    redirect_to user_url(@user)
  end
  
  private

    def student_params
      params.require(:student).permit(:name, :gender, :student_class, :date_known, :employment)
    end
    
     # Confirms the correct user.
    def correct_user
      @student = Student.find(params[:id])
      @user = @student.user
      redirect_to(root_url) unless current_user?(@user)
    end
  
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_student.html.erb
<li id="student-<%= student.id %>">
  <span class="user"><%= link_to student.name, student %> </span>
  <span class="timestamp">
    Created <%= time_ago_in_words(student.created_at) %> ago.
  </span>
</li>

app/views/students/edit.html.erb
<% provide(:title, "Edit Student") %>
<h1>Update Student</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@student) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= hidden_field_tag :user, @student.user %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      
    <div class="radio-inline">
      <%= f.radio_button(:gender, 1) %>
      <%= f.label(:gender, "Male", value:1) %> 
      <span style="margin-left:2em"><%= f.radio_button(:gender, 0) %> </span>
      <%= f.label(:gender, "Female", value:0) %>
   </div>
    <p></p>
    
      <%= f.label :date_known %>
      <%= f.date_field :date_known, class: 'form-control'%>

      <%= f.label :student_class, "Class student has been in" %>
      <%= f.text_field :student_class, class: 'form-control' %>
      
      <%= f.label :employment, "Student Research/Employment" %>
      <%= f.text_field :employment, class: 'form-control' %>

      <%= f.submit "Save Changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/students/new.html.erb
<% provide(:title, 'Create Student') %>
<h1>New Student</h1>

<div class="row">
 <div class="col-md-6 col-md-offset-3">
    <%= form_for(@student) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
      <%= hidden_field_tag :user, @student.user %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

    <div class="radio-inline">
      <%= f.radio_button(:gender, 1) %>
      <%= f.label(:gender, "Male", value:1) %> 
      <span style="margin-left:2em"><%= f.radio_button(:gender, 0) %> </span>
      <%= f.label(:gender, "Female", value:0) %>
   </div>
    <p></p>
    
      <%= f.label :date_known %>
      <%= f.date_field :date_known, class: 'form-control'%>

      <%= f.label :student_class, "Class student has been in" %>
      <%= f.text_field :student_class, class: 'form-control' %>
      
      <%= f.label :employment, "Student Research/Employment" %>
      <%= f.text_field :employment, class: 'form-control' %>

      <%= f.submit "Create Student", class: "btn btn-primary" %>
    <% end %>
   
  </div>
</div>

app/views/students/show.html.erb
<% provide(:title, @student.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="student_info">
      
       <h4> <span style="padding-top:0.6em"><%= @student.name %></span> </h4>
       <p><%=link_to "Edit", edit_student_path(@student) %> | <%= link_to "Delete", @student, method: :delete,
                                  data: { confirm: "You sure?" } %></p>
       <p><%=link_to "Create New Letter", new_student_letter_path(@student) %></p>
       <p>Professor: <%= @student.user.name %> </p>
       <% if @student.gender == 1%>
       <span><p>Gender: Male</p></span>
       <% else %>
       <span><p>Gender: Female</p></span>
       <% end %>
       <% if @student.letters.size!=0%>
           <%@letters = @student.letters%>
           <p>Letter Ratings: 
               <%@letters.each do |l|%>
                   <%=link_to l.rating, student_letter_path(@student, l)%>
               <%end%>
               </p>
        <%end%>
       <% if !@student.student_class.blank?%>
       <span><p>Taken Class: <%= @student.student_class %></p></span>
       <%end%>
       <% if !@student.employment.blank?%>
       <span><p>Research/Employment: <%= @student.employment %></p></span>
       <%end%>
       <% if !@student.date_known.blank?%>
       <span><p>Known since: <%= @student.date_known.strftime("%B %d, %Y") %></p></span>
       <%end%>
       
    </section>
  </aside>
</div>